-- item categories generating total sales greater than ₹50,000
select item_type,
       sum(sales) as total_sales
from blinkit_sales
group by item_type
having total_sales > 50000
order by total_sales desc;

-- outlet types have an average sales value greater than ₹200
select outlet_type,
	   avg(sales) as avg_sales
from blinkit_sales
group by outlet_type
having avg_sales>200
order by avg_sales desc;

-- outlet location with total sales greater than ₹100,000
select outlet_location_type,
	   sum(sales) as total_sales
from blinkit_sales
group by outlet_location_type
having total_sales > 100000
order by total_sales desc;

-- item categories with more than 400 products
select item_type,
       count(item_type) as no_of_products
from blinkit_sales
group by item_type
having no_of_products > 400
order by no_of_products desc;

-- outlet establishment years with average rating greater than 4.0
select outlet_establishment_year,
	   avg(rating) as avg_rating
from blinkit_sales
group by outlet_establishment_year
having avg_rating >4.0
order by outlet_establishment_year;

-- item categories with average item visibility greater than 0.07
select item_type,
	   avg(item_visibility) as avg_item_visibility
from blinkit_sales
group by item_type
having avg_item_visibility>0.07
order by avg_item_visibility desc;

-- outlet sizes with average sales value greater than the overall average sales
select outlet_size, avg(sales)
from blinkit_sales
group by outlet_size
having avg(sales)>
(
select avg(sales)
from blinkit_sales
)
order by avg(sales) desc;

-- item categories with total sales greater than the overall average sales
select item_type,
       sum(sales) as total_sale
from blinkit_sales
group by item_type
having total_sale >
(
select avg(sales)
from blinkit_sales
)
order by total_sale;

-- Categorize each product based on its sales into:
-- High Sales (> 250),Medium Sales (100–250),Low Sales (< 100)
select item_identifier,sales,
       case
          when sales>250 then
'High sales'
          when sales>=100 and sales<=250 then
'Medium sales'
           when sales<100 then
'low sales'
end as sales_category
from blinkit_sales
order by sales desc;

-- Categorize each product based on its rating into:
-- Excellent (≥ 4.5) , Good (4.0–4.49),Average (< 4.0)
select item_identifier,rating,
       case
		when rating>=4.5 then 'excellent'
        when rating between 4.0 and 4.49 then 'good'
        when rating <4.0 then 'average'
        end as raateng_category
from blinkit_sales
order by rating ;

-- Categorize outlets into:
-- Old Outlet (before 2000),New Outlet (2000 or later)
select item_type, outlet_establishment_year,
        case
           when outlet_establishment_year<=2013 then 'old outlet'
           when outlet_establishment_year>2013 then 'new outlet'
           end as outlet_establishment_year_category
from blinkit_sales;

-- Count the number of products in each sales category
select sales_category,
       count(*) as no_of_products
from(
select case
         when sales>200 then 'high sale'
         when sales between 100 and 200 then 'medium sale'
         else 'low sale'
         end as sales_category
	from blinkit_sales
    )as t
    group by sales_category;
    
-- The average sales for each sales category
select sales_category,
       avg(sales) as average_sales
from(
select sales,
	     case
         when sales>200 then 'high sale'
         when sales between 100 and 200 then 'medium sale'
         else 'low sale'
         end as sales_category
	from blinkit_sales
    )as t
    group by sales_category;
    
-- The average rating for each rating category
SELECT
    CASE
        WHEN rating >= 4.5 THEN 'Excellent'
        WHEN rating >= 4.0 THEN 'Good'
        ELSE 'Average'
    END AS rating_category,
    AVG(rating) AS avg_rating
FROM blinkit_sales
GROUP BY rating_category
ORDER BY avg_rating DESC;

-- the total sales generated by:
-- Old Outlets , New Outlets
SELECT
    CASE
        WHEN outlet_establishment_year < 2000 THEN 'Old Outlet'
        ELSE 'New Outlet'
    END AS outlet_category,
    ROUND(SUM(sales),2) AS total_sales
FROM blinkit_sales
GROUP BY outlet_category
ORDER BY total_sales DESC;

-- the item category with the highest total sales using a CTE
With category_sales as
(
    SELECT item_type,
           SUM(sales) as total_sales
    FROM blinkit_sales
    GROUP BY item_type
)
SELECT *
FROM category_sales
ORDER BY total_sales DESC
LIMIT 1;

-- The second highest-selling item category using CTE + DENSE_RANK
With category_sales as
(
	select item_type,
           sum(sales) as total_sales,
           dense_rank() over(order by sum(sales) desc)as rnk
	from blinkit_sales
    group by item_type
)
SELECT
    item_type,
    total_sales
FROM category_sales
WHERE rnk = 2;

-- the top 3 item categories by total sales using CTE + DENSE_RANK()
with category_sales as
(  
  select item_type,
         sum(sales) as total_sales,
  dense_rank() over(order by sum(sales) desc) as rnk
  from blinkit_sales
    group by item_type
)
SELECT
    item_type,
    total_sales
FROM category_sales
WHERE rnk <=3;

-- item category with the highest average rating using a CTE
with category_sales as
(
  select item_type,
         avg(rating) as avg_rating,
         dense_rank() over (order by avg(rating) desc) as rnk
         from blinkit_sales
    group by item_type
)
SELECT
    item_type,
    avg_rating
FROM category_sales
WHERE rnk =1;

-- The outlet with the highest total sales using a CTE
with category_sales as
(
  select outlet_type,
		 sum(sales) as total_sales
         from blinkit_sales
    group by outlet_type
)
SELECT
    outlet_type,
    total_sales
FROM category_sales
order by total_sales desc
Limit 1;

-- highest selling outlet in each outlet location
with category_sales as
(
  select outlet_location_type,
		outlet_type,
		 sum(sales) as total_sales,
   dense_rank() over ( partition by outlet_location_type order by sum(sales) desc) as rnk
   from blinkit_sales
    group by outlet_location_type, outlet_type
)
SELECT
    outlet_location_type,
    outlet_type,
    total_sales
FROM category_sales
where rnk=1;

-- the highest-selling outlet size
WITH outlet_sales AS
(
    SELECT outlet_size,
           SUM(sales) AS total_sales
    FROM blinkit_sales
    GROUP BY outlet_size
)
SELECT *
FROM outlet_sales
ORDER BY total_sales DESC
LIMIT 1;

-- Categories with Average Sales Greater Than Overall Average
WITH category_avg AS
(
    SELECT item_type,
           AVG(sales) AS avg_sales
    FROM blinkit_sales
    GROUP BY item_type
)
SELECT item_type,
       avg_sales
FROM category_avg
WHERE avg_sales >
(
    SELECT AVG(sales)
    FROM blinkit_sales
)
ORDER BY avg_sales DESC;

-- Top-Selling Product in Each Category
WITH product_rank AS
(
    SELECT item_identifier,
           item_type,
           sales,
           DENSE_RANK() OVER
           (
               PARTITION BY item_type
               ORDER BY sales DESC
           ) AS rnk
    FROM blinkit_sales
)
SELECT item_identifier,
       item_type,
       sales
FROM product_rank
WHERE rnk = 1;

-- Assign ROW_NUMBER Based on Sales
SELECT item_identifier,
       item_type,
       sales,
       ROW_NUMBER() OVER(ORDER BY sales DESC) AS row_num
FROM blinkit_sales;

-- Assign RANK Based on Sales
SELECT item_identifier,
       item_type,
       sales,
       RANK() OVER(ORDER BY sales DESC) AS sales_rank
FROM blinkit_sales;

-- Assign DENSE_RANK Based on Sales
SELECT item_identifier,
       item_type,
       sales,
       DENSE_RANK() OVER(ORDER BY sales DESC) AS dense_sales_rank
FROM blinkit_sales;

-- Rank Products Within Each Outlet
SELECT outlet_identifier,
       item_identifier,
       item_type,
       sales,
       DENSE_RANK() OVER
       (
           PARTITION BY outlet_identifier
           ORDER BY sales DESC
       ) AS outlet_product_rank
FROM blinkit_sales;

-- Rank Products Within Each Category
SELECT item_type,
       item_identifier,
       sales,
       DENSE_RANK() OVER
       (
           PARTITION BY item_type
           ORDER BY sales DESC
       ) AS category_product_rank
FROM blinkit_sales;

-- Highest-Selling Product in Every Outlet
WITH outlet_product_rank AS
(
    SELECT outlet_identifier,
           item_identifier,
           item_type,
           sales,
           DENSE_RANK() OVER
           (
               PARTITION BY outlet_identifier
               ORDER BY sales DESC
           ) AS rnk
    FROM blinkit_sales
)
SELECT outlet_identifier,
       item_identifier,
       item_type,
       sales
FROM outlet_product_rank
WHERE rnk = 1;

-- Highest-Rated Product in Every Category
WITH category_rating_rank AS
(
    SELECT item_type,
           item_identifier,
           rating,
           DENSE_RANK() OVER
           (
               PARTITION BY item_type
               ORDER BY rating DESC
           ) AS rnk
    FROM blinkit_sales
)
SELECT item_type,
       item_identifier,
       rating
FROM category_rating_rank
WHERE rnk = 1;

-- Duplicate Product IDs
SELECT item_identifier,
       COUNT(*) AS duplicate_count
FROM blinkit_sales
GROUP BY item_identifier
HAVING COUNT(*) > 1
ORDER BY duplicate_count DESC;

-- Products Available in More Than One Outlet
SELECT item_identifier,
       COUNT(*) AS duplicate_count
FROM blinkit_sales
GROUP BY item_identifier
HAVING COUNT(*) > 1
ORDER BY duplicate_count DESC;

-- Second Highest-Selling Product
WITH product_rank AS
(
    SELECT item_identifier,
           item_type,
           sales,
           DENSE_RANK() OVER(ORDER BY sales DESC) AS rnk
    FROM blinkit_sales
)
SELECT item_identifier,
       item_type,
       sales
FROM product_rank
WHERE rnk = 2;

         
         

 







   









       