-- total sales generated by each item type
select sum(sales) as total_sales,
       item_type
from blinkit_sales
group by item_type
order by total_sales desc;

-- average sales for each item type
select avg(sales) as avg_sales,
       item_type
from blinkit_sales
group by item_type
order by avg_sales desc;

-- 5 item types generated the highest total sales
select sum(sales) as total_sales,
       item_type
from blinkit_sales
group by item_type
order by total_sales desc
limit 5;

-- 5 item types generated the lowest total sales
select sum(sales) as total_sales,
       item_type
from blinkit_sales
group by item_type
order by total_sales 
limit 5;

-- total sales by item fat content
select sum(sales) as total_sales,
       item_fat_content
from blinkit_sales
group by item_fat_content
order by total_sales desc;

-- total sales by outlet type
select sum(sales) as total_sales,
       outlet_type
from blinkit_sales
group by outlet_type
order by total_sales desc;

-- average sales by outlet type
select avg(sales) as avg_sales,
       outlet_type
from blinkit_sales
group by outlet_type
order by avg_sales desc;

-- outlet type generated the highest sales
select sum(sales) as total_sales,
       outlet_type
from blinkit_sales
group by outlet_type
order by total_sales desc
limit 1;

-- total sales by outlet size
select sum(sales) as total_sales,
       outlet_size
from blinkit_sales
group by outlet_size
order by total_sales desc;

-- average sales by outlet size
select avg(sales) as avg_sales,
       outlet_size
from blinkit_sales
group by outlet_size
order by avg_sales desc;

-- total sales by outlet location type
select sum(sales) as total_sales,
       outlet_location_type
from blinkit_sales
group by outlet_location_type
order by total_sales desc;

-- outlet location contributes the highest sales
select sum(sales) as total_sales,
       outlet_location_type
from blinkit_sales
group by outlet_location_type
order by total_sales desc
limit 1;

-- average rating for each item type
select avg(rating) as avg_rating,
       item_type
from blinkit_sales
group by item_type
order by avg_rating desc;

-- item category having highest average rating
select avg(rating) as avg_rating,
       item_type
from blinkit_sales
group by item_type
order by avg_rating desc
limit 1;

-- average rating by outlet type
select avg(rating) as avg_rating,
       outlet_type
from blinkit_sales
group by outlet_type
order by avg_rating desc;

-- average item weight for each item type
SELECT item_type,
       AVG(CAST(item_weight AS DECIMAL(10,2)))AS avg_item_weight
FROM blinkit_sales
WHERE item_weight IS NOT NULL
  AND item_weight <> ''
GROUP BY item_type
ORDER BY avg_item_weight DESC;

-- average item visibility for each outlet type
select avg(item_visibility) as avg_item_visibility,
       outlet_type
from blinkit_sales
group by outlet_type
order by avg_item_visibility desc;

-- outlet having highest average item visibility
select avg(item_visibility) as avg_item_visibility,
       outlet_type
from blinkit_sales
group by outlet_type
order by avg_item_visibility desc
limit 1;

-- total sales for each outlet establishment year
select sum(sales) as total_sales,
       Outlet_Establishment_year
from blinkit_sales
group by Outlet_Establishment_year
order by total_sales desc;

-- establishment year generating highest sales
select sum(sales) as total_sales,
       Outlet_Establishment_year
from blinkit_sales
group by Outlet_Establishment_year
order by total_sales desc
limit 1;










